config/routes.rb
TaskTracker::Application.routes.draw do

  root :to => 'tasks#index' 
  resources :tasks do
    collection do
      get  :today
      get  :today_submit_test
      get  :today_test_over
      get  :today_deliver
      get  :search
      get  :by_user
      get  :by_state
      get  :me
      get  :thisweek
      get  :thisweek_submit_test
      get  :thisweek_test_over
      get  :thisweek_deliver
    end
    resources :task_histories
  end

  resources :users
end

app/models/task.rb
# encoding: utf-8
class Task < ActiveRecord::Base
  belongs_to :state
  has_many :task_user_ships,:dependent => :destroy
  has_many :users,:through => :task_user_ships
  has_many :task_histories,:dependent => :destroy
  has_many :attachments,:dependent => :destroy
  accepts_nested_attributes_for :attachments,:allow_destroy => true
  validates_presence_of :name,:message => "任务名不能为空"
  validates_format_of :submit_test_date,:submit_test_over_date,:submit_deliver_date,:allow_nil => true,:with => /(([0-9]{3}[1-9]|[0-9]{2}[1-9][0-9]{1}|[0-9]{1}[1-9][0-9]{2}|[1-9][0-9]{3})-(((0[13578]|1[02])-(0[1-9]|[12][0-9]|3[01]))|((0[469]|11)-(0[1-9]|[12][0-9]|30))|(02-(0[1-9]|[1][0-9]|2[0-8]))))|((([0-9]{2})(0[48]|[2468][048]|[13579][26])|((0[48]|[2468][048]|[3579][26])00))-02-29)/
  
  scope :today_test,where(["submit_test_date >= ? and submit_test_date <= ?",Time.now.beginning_of_day,Time.now.end_of_day])
  scope :today_test_over,where(["submit_test_over_date >= ? and submit_test_over_date <= ?",Time.now.beginning_of_day,Time.now.end_of_day])
  scope :today_deliver,where(["submit_deliver_date >= ? and submit_deliver_date <= ?",Time.now.beginning_of_day,Time.now.end_of_day])
  scope :today_all,where(["(submit_deliver_date >= ? and submit_deliver_date <= ?) or (submit_test_over_date >= ? and submit_test_over_date <= ?) or (submit_test_date >= ? and submit_test_date <= ?)",Time.now.beginning_of_day,Time.now.end_of_day,Time.now.beginning_of_day,Time.now.end_of_day,Time.now.beginning_of_day,Time.now.end_of_day])

  scope :thisweek_test,where(["submit_test_date >= ? and submit_test_date <= ?",Time.now.beginning_of_week,Time.now.end_of_week])
  scope :thisweek_test_over,where(["submit_test_over_date >= ? and submit_test_over_date <= ?",Time.now.beginning_of_week,Time.now.end_of_week])
  scope :thisweek_deliver,where(["submit_deliver_date >= ? and submit_deliver_date <= ?",Time.now.beginning_of_week,Time.now.end_of_week])
  scope :thisweek_all,where(["(submit_deliver_date >= ? and submit_deliver_date <= ?) or (submit_test_over_date >= ? and submit_test_over_date <= ?) or (submit_test_date >= ? and submit_test_date <= ?)",Time.now.beginning_of_week,Time.now.end_of_week,Time.now.beginning_of_week,Time.now.end_of_week,Time.now.beginning_of_week,Time.now.end_of_week])
end

app/controllers/tasks_controller.rb
#encoding: utf-8 
class TasksController < ApplicationController
  def index
    order_by = order_through_link
    @tasks = Task.paginate :page=>params[:page],:order=> order_by,:per_page => 20
    @states = State.all
    @users_developers = get_user_by_dep(1)
    @users_testers = get_user_by_dep(2)
  end
  
  def show
    @task = Task.find(params[:id])
    @task_history = TaskHistory.new
    @task_history.attachments.build
  end

  def edit
    @task = Task.find(params[:id])
    @users_developers = get_user_by_dep(1)
    @users_testers = get_user_by_dep(2)
    if @task.attachments.blank?
        @task.attachments.build
    end
  end

  def update
    params[:task][:user_ids] ||= []  
    @task = Task.find(params[:id])
   if @task.update_attributes(params[:task])
     flash[:notice] = '任务已成功更新'
     redirect_to task_url(@task)
   else
     render :action => "edit"
   end
  end

  def new
    @task = Task.new
    @users_developers = get_user_by_dep(1)
    @users_testers = get_user_by_dep(2)
    @task.attachments.build
  end

  def create
    params[:task][:user_ids] ||= []
    @task = Task.new(params[:task])
    if @task.save
      flash[:notice] = '任务已成功创建'
      redirect_to tasks_url
    else
      render :action => 'new'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = '任务已成功删除'
    redirect_to tasks_url
  end
  #添加方法
  def today
    @tasks = Task.today_all
    get_today_task_count
    render :action => 'today'
  end
  
  def today_submit_test
    @tasks = Task.today_test
    get_today_task_count
    render :action => 'today'
  end

  def today_test_over
    @tasks = Task.today_test_over
    get_today_task_count
    render :action => 'today'
  end

  def today_deliver
    @tasks = Task.today_deliver
    get_today_task_count
    render :action => 'today'
  end

  def thisweek
    @tasks = Task.thisweek_all
    get_week_task_count
    render :action => 'thisweek'
  end
  
  def thisweek_submit_test
    @tasks = Task.thisweek_test
    get_week_task_count
    render :action => 'thisweek'
  end

  def thisweek_test_over
    @tasks = Task.thisweek_test_over
    get_week_task_count
    render :action => 'thisweek'
  end

  def thisweek_deliver
    @tasks = Task.thisweek_deliver
    get_week_task_count
    render :action => 'thisweek'
  end
  
  def search
    @tasks = Task.where( [ "name like ?", "%#{params[:keyword]}%" ])
  end

  def by_user
    tasks_total = get_tasks_by_user(params[:userid])
    @tasks = tasks_total.paginate :page=>params[:page],:order=>'created_at desc',:per_page => 20
    @states = State.all
    @users_developers = get_user_by_dep(1)
    @users_testers = get_user_by_dep(2)
    flash.now[:notice] = User.find(params[:userid]).name+'的任务有'+tasks_total.size.to_s+'个'
    render :template => 'tasks/filter'
  end

  def by_state
    tasks_total = Task.where([ "state_id = ?",params[:stateid] ] )
    @tasks = tasks_total.paginate :page=>params[:page],:order=>'created_at desc',:per_page => 20
    @states = State.all
    @users_developers = get_user_by_dep(1)
    @users_testers = get_user_by_dep(2)
    flash.now[:notice] = State.find(params[:stateid]).name+'的任务有'+tasks_total.size.to_s+'个'
    render :template => 'tasks/filter'
  end

  def me
    user = User.find_by_bind_ip(request.remote_ip)
    unless user.blank?
      @tasks = get_tasks_by_user(user.id)
      @user_name = user.name
    end
  end
  
  #私有方法
  private
  #根据主键Id暂时写死要查询的user分类
  def get_user_by_dep(dep_id)
    users = User.where(:department_id=> dep_id)
  end

  def get_tasks_by_user(user)
    userselected = User.find(user)
    tasks = []
    not_deliver_tasks = Task.where("state_id != ? ",7);
    for d in not_deliver_tasks
      if d.users.include?(userselected)
        tasks << d
      end
    end
    tasks
  end

  def get_today_task_count
    @tasks_test_count = Task.today_test.size.to_s
    @tasks_test_over_count = Task.today_test_over.size.to_s
    @tasks_deliver_count = Task.today_deliver.size.to_s
  end

  def get_week_task_count
    @tasks_test_count = Task.thisweek_test.size.to_s
    @tasks_test_over_count = Task.thisweek_test_over.size.to_s
    @tasks_deliver_count = Task.thisweek_deliver.size.to_s
  end

  def order_through_link
    case params[:order_by]
    when "state_id"
      order_by =  params[:order_by] + ' asc'
    when nil
      order_by = 'created_at desc'
    else
      order_by =  params[:order_by] + ' desc'
    end
    return order_by
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def state_options
    State.all.map{|s| [s.name,s.id]}
  end
  def task_user_by_dep(task,dep_id)
    users = []
    for u in task.users
      if u.department.id == dep_id
        users << u.name
     end 
    end
    users.join("+")
  end
end

app/views/tasks/_tasklist.html.erb
    <% @tasks.each do |task|%>
    <tr>
      <td class="task_table_name"><%= link_to task.name,task_path(task) %></td>
      <td><%= task.require_people_name %></td>
      <td><%= task_user_by_dep task,1 %></td>
      <td><%= task_user_by_dep task,2 %></td>
      <td><%= convet_time_to_m_d task.created_at %></td>
      <td><%= convet_time_to_m_d task.submit_test_date %></td>
      <td><%= convet_time_to_m_d task.submit_test_over_date %></td>
      <td><%= convet_time_to_m_d task.submit_deliver_date %></td>
      <td><span class="task_state"><%=link_to task.state.name,edit_task_path(task) %></span></td>
    </tr>
    <% end %>
      

app/views/tasks/edit.html.erb
<div class="edit_task_page_title">
编辑任务：<%=link_to @task.name,@task %>
</div>
 <% if @task.errors.any? %>
    <div id="error_explanation">
      <ol>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ol>
    </div>
  <% end %>
    <div class="edit_task_form">
  <%= form_for @task,:html => { :multipart => true } do |t|%>
    <table class="edit_task_table">
      <tr>
        <td class="task_attr_name">任务名：</td><td><%= t.text_field :name,:required=>true %></td>
      </tr>
      <tr>
        <td class="task_attr_name">任务状态：</td><td><%= t.select :state_id, state_options %></td>
      </tr>
      <tr>
        <td class="task_attr_name">提测时间：</td><td><%= t.text_field :submit_test_date,:pattern => '(([0-9]{3}[1-9]|[0-9]{2}[1-9][0-9]{1}|[0-9]{1}[1-9][0-9]{2}|[1-9][0-9]{3})-(((0[13578]|1[02])-(0[1-9]|[12][0-9]|3[01]))|((0[469]|11)-(0[1-9]|[12][0-9]|30))|(02-(0[1-9]|[1][0-9]|2[0-8]))))|((([0-9]{2})(0[48]|[2468][048]|[13579][26])|((0[48]|[2468][048]|[3579][26])00))-02-29)',:title=>'例如：2011-05-06',:class=>'datepicker'%></td>
      </tr>
      <tr>
        <td class="task_attr_name">测试完成：</td><td><%= t.text_field :submit_test_over_date,:pattern => '(([0-9]{3}[1-9]|[0-9]{2}[1-9][0-9]{1}|[0-9]{1}[1-9][0-9]{2}|[1-9][0-9]{3})-(((0[13578]|1[02])-(0[1-9]|[12][0-9]|3[01]))|((0[469]|11)-(0[1-9]|[12][0-9]|30))|(02-(0[1-9]|[1][0-9]|2[0-8]))))|((([0-9]{2})(0[48]|[2468][048]|[13579][26])|((0[48]|[2468][048]|[3579][26])00))-02-29)',:title=>'例如：2011-05-06',:class=>'datepicker'%></td>
      </tr>
      <tr>
        <td class="task_attr_name">发外网时间：</td><td><%= t.text_field :submit_deliver_date,:pattern => '(([0-9]{3}[1-9]|[0-9]{2}[1-9][0-9]{1}|[0-9]{1}[1-9][0-9]{2}|[1-9][0-9]{3})-(((0[13578]|1[02])-(0[1-9]|[12][0-9]|3[01]))|((0[469]|11)-(0[1-9]|[12][0-9]|30))|(02-(0[1-9]|[1][0-9]|2[0-8]))))|((([0-9]{2})(0[48]|[2468][048]|[13579][26])|((0[48]|[2468][048]|[3579][26])00))-02-29)',:title=>'例如：2011-05-06',:class=>'datepicker'%></td>
      </tr>
      <tr>
        <td class="task_attr_name">需求人员：</td>
        <td>
          <%= t.text_field :require_people_name %>
        </td>
      </tr>
      <tr>
        <td class="task_attr_name">开发人员：</td>
        <td>
          <% unless  @users_developers.blank? %>
           <% for user in @users_developers%>
              <%= check_box_tag "task[user_ids][]",user.id,@task.users.include?(user)%><%= user.name%>
            <%end%>
          <%end%>
        </td>
      </tr>
      <tr>
        <td class="task_attr_name">测试人员：</td>
        <td>
          <% unless  @users_testers.blank? %>
          <% for user in @users_testers%>
            <%= check_box_tag "task[user_ids][]",user.id,@task.users.include?(user)%><%= user.name%>
          <%end%>
        <%end%>
        </td>
      </tr>
      <tr>
        <td class="task_attr_name">备注：</td><td><%= t.text_area :description%></td>
      </tr>
      <% unless @task.attachments.blank? %>
      <tr>
        <td class="task_attr_name">原附件：</td><td>
          <% if  @task.attachments.count == 0 %>
            无
          <%else%>
            <% for attachment in @task.attachments %> 
              <%= link_to attachment.pic.original_filename, attachment.pic.url %>
            <% end %>
          <%end%>
        </td>
      </tr>
      <%end%>
      <%= t.fields_for :attachments do |builder| %>
     <tr>
        <td class="task_attr_name">附件：</td>   
        <td><%= builder.file_field :pic %> <%= builder.check_box :_destroy %>删除附件 </td>
     </tr>
      <% end %> 
    </table>
    <div class="edit_task_submit_outer"> <%= t.submit '更新任务' %> </div>
  <%end%>
</div>
<div class="related_link_group">
  <%= link_to raw('<span class="leftarrow icon"></span>返回任务列表'), tasks_path,:class=>'back button'%>
  <%= link_to raw('<span class="trash icon"></span>删除此任务') , @task,:method=> :delete,:confirm => '确定删除？',:class=>'negative button'%>
</div>

app/views/tasks/filter.html.erb
<nav>
<%= link_to "全部",tasks_path,:class=>"selected" %>
<%= link_to "本周",thisweek_tasks_path %>
<%= link_to "今日",today_tasks_path%>
<%= link_to "我的任务",me_tasks_path%>
<div class="new_task_btn_outer"><%= link_to raw('<span class="plus icon"></span>添加新任务'),new_task_path,:class => "button " %></div>
</nav>
<div class="sub_nav">
  <% unless @states.blank?%>
    <span class="by_group_check">
      <div>任务状态</div>
      <div class="group_list">
    <% for state in @states%>
      <%= link_to state.name,by_state_tasks_path+"?stateid="+state.id.to_s%>
    <%end%>
      </div>
    </span>
  <%end%>
  <% unless @users_developers.blank?%>
    <span class="by_group_check">
      <div>开发人员</div>
      <div class="group_list">
    <% for user in @users_developers%>
      <%= link_to user.name,by_user_tasks_path+"?userid="+user.id.to_s%>
    <%end%>
      </div>
    </span>
  <%end%>

  <% unless @users_testers.blank?%>
    <span class="by_group_check">
      <div>测试人员</div>
      <div class="group_list">
    <% for user in @users_testers%>
      <%= link_to user.name,by_user_tasks_path+"?userid="+user.id.to_s%>
    <%end%>
      </div>
    </span>
  <%end%>
</div>
<% if @tasks.blank?%>
  <div class="no_task">没有任务</div>
<%else%>
  <div class="task_list">
  <table>
    <tr class="include_link_th">
      <th>任务名</th><th>需求人员</th><th>开发人员</th><th>测试人员</th><th>需求提交</th><th>提交测试</th><th>测试完成</th><th>发外网</th><th>当前状态</th>
    </tr>
    <%= render :partial => "tasks/tasklist" %>
      </table>           
</div>
<%end%>
<%= will_paginate @tasks %>

app/views/tasks/index.html.erb
<nav>
<%= link_to "全部",tasks_path,:class=>"selected" %>
<%= link_to "本周",thisweek_tasks_path %>
<%= link_to "今日",today_tasks_path%>
<%= link_to "我的任务",me_tasks_path%>
<div class="new_task_btn_outer"><%= link_to raw('<span class="plus icon"></span>添加新任务'),new_task_path,:class => "button " %></div>
</nav>
<div class="sub_nav">
  <% unless @states.blank?%>
    <span class="by_group_check">
      <div>任务状态</div>
      <div class="group_list">
    <% for state in @states%>
      <%= link_to state.name,by_state_tasks_path+"?stateid="+state.id.to_s%>
    <%end%>
      </div>
    </span>
  <%end%>
  <% unless @users_developers.blank?%>
    <span class="by_group_check">
      <div>开发人员</div>
      <div class="group_list">
    <% for user in @users_developers%>
      <%= link_to user.name,by_user_tasks_path+"?userid="+user.id.to_s%>
    <%end%>
      </div>
    </span>
  <%end%>

  <% unless @users_testers.blank?%>
    <span class="by_group_check">
      <div>测试人员</div>
      <div class="group_list">
    <% for user in @users_testers%>
      <%= link_to user.name,by_user_tasks_path+"?userid="+user.id.to_s%>
    <%end%>
      </div>
    </span>
  <%end%>
</div>
<% if @tasks.blank?%>
  <div class="no_task">没有任务</div>
<%else%>
  <div class="task_list">
  <table>
    <tr class="include_link_th">
      <th>任务名</th><th>需求人员</th><th>开发人员</th><th>测试人员</th><th><%= link_to '需求提交',tasks_path %></th><th><%= link_to '提交测试',tasks_path + '?order_by=submit_test_date'%></th><th><%= link_to '测试完成',tasks_path + '?order_by=submit_test_over_date'%></th><th><%= link_to '发外网',tasks_path + '?order_by=submit_deliver_date'%></th><th><%= link_to '当前状态',tasks_path + '?order_by=state_id'%></th>
    </tr>
    <%= render :partial => "tasks/tasklist" %>
      </table>           
</div>
<%end%>
<%= will_paginate @tasks %>
      

app/views/tasks/me.html.erb
<nav>
<%= link_to "全部",tasks_path %>
<%= link_to "本周",thisweek_tasks_path %>
<%= link_to "今日",today_tasks_path%>
<%= link_to "我的任务",today_tasks_path,:class=>"selected"%>
</nav>
<div class="sub_nav">
	<div class="subnav_blank">
	 <% if @user_name.blank? %>
		不知道你是谁，请告诉管理员你的名字和IP
	 <%else%>
		Hi,<%= @user_name %>！你共有个<%= @tasks.size.to_s%>任务
	 <%end%>
	</div>
      </div>
      <% if @tasks.blank?%>
  <div class="no_task">没有任务</div>
<%else%>
  <div class="task_list">
  <table>
    <tr class="include_link_th">
      <th>任务名</th><th>需求人员</th><th>开发人员</th><th>测试人员</th><th>需求提交</th><th>提交测试</th><th>测试完成</th><th>发外网</th><th>当前状态</th>
    </tr>
    <%= render :partial => "tasks/tasklist" %>
      </table>           
</div>
<%end%>

app/views/tasks/search.html.erb
<nav>
<%= link_to "全部",tasks_path,:class=>"selected" %>
<%= link_to "本周",thisweek_tasks_path %>
<%= link_to "今日",today_tasks_path%>
<%= link_to "我的任务",me_tasks_path%>
</nav>
<div class="sub_nav">
  <div class="subnav_blank">
    搜索出<%=@tasks.size.to_s %>个任务
  </div>	
</div>
<% if @tasks.blank?%>
  <div class="no_task">没有任务</div>
<%else%>
  <div class="task_list">
  <table>
    <tr class="include_link_th">
      <th>任务名</th><th>需求人员</th><th>开发人员</th><th>测试人员</th><th>需求提交</th><th>提交测试</th><th>测试完成</th><th>发外网</th><th>当前状态</th>
    </tr>
    <%= render :partial => "tasks/tasklist" %>
      </table>           
</div>
<%end%>
<%= link_to raw('<span class="leftarrow icon"></span>返回任务列表'), tasks_path,:class=>'back button'%>

app/views/tasks/show.html.erb
<div class="edit_task_page_title">
  <%= @task.name %>
</div>
<div class="task_info">
  <div id="task_show_view_state"><%= @task.state.name %></div>
  <div class="task_info_content">
  <table class="edit_task_table">
    <tr>
      <td class="task_attr_name">任务名称：</td><td><%= @task.name %></td>
    </tr>
    <tr>
      <td class="task_attr_name">提测时间：</td><td><%=convet_time_to_m_d @task.submit_test_date%></td>
    </tr>
    <tr>
      <td class="task_attr_name">测试完成：</td><td><%=convet_time_to_m_d @task.submit_test_over_date%></td>
    </tr>
    <tr>
      <td class="task_attr_name">发外网时间：</td><td><%=convet_time_to_m_d @task.submit_deliver_date%></td>
    </tr>
     <tr>
      <td class="task_attr_name">需求人员：</td><td><%=@task.require_people_name%></td>
    </tr>
     <tr>
      <td class="task_attr_name">开发人员：</td><td><%=task_user_by_dep @task,1%></td>
    </tr>
     <tr>
      <td class="task_attr_name">测试人员：</td><td><%=task_user_by_dep @task,2%></td>
    </tr>
    <tr>
      <td class="task_attr_name">备注：</td><td><%= @task.description %></td>
    </tr>
    <tr>
      <td class="task_attr_name">附件：</td><td><% for attachment in @task.attachments %> <%= link_to attachment.pic.original_filename, attachment.pic.url %><% end %></td>
    </tr>
  </table>
  </div>
  <div class="set_task_history_btn">
    <%= link_to raw('<span class="leftarrow icon"></span>返回任务列表'), tasks_path,:class=>'back button' %><br/>
    <a href="#" class="button" id="apply_to_test_in_task_history" name="3"><span class="uparrow icon"></span>提交测试</a><br/>
    <a href="#" class="negative button" id="test_failed_in_task_history" name="4"><span class="reload icon"></span>测试打回</a><br/>
    <a href="#" class="positive button" id="test_pass_in_task_history" name="5"><span class="check icon"></span>测试通过</a>
</div>
<div class="clear"></div>
</div>


<%= render :partial => "task_histories/task_history" %>
<div id="task_history_form">
<%= form_for @task_history, :url => task_task_histories_path(@task),:html => { :multipart => true } do |f| %>
  <%= f.text_area :content,:required=>true %>
  <%= f.fields_for :attachments do |builder| %>
    <%= builder.file_field :document %>
  <% end %>
  <%= f.select :state_id, state_options %>
  <%= f.submit '提交' %>
 <% end %>
</div>

app/views/tasks/thisweek.html.erb
<nav>
<%= link_to "全部",tasks_path %>
<%= link_to "本周",thisweek_tasks_path,:class=>"selected" %>
<%= link_to "今日",today_tasks_path %>
<%= link_to "我的任务",me_tasks_path%>
</nav>
<div class="sub_nav">
  <%=link_to "需提测("+@tasks_test_count+")",thisweek_submit_test_tasks_path %>
  <%=link_to "需测试完成("+@tasks_test_over_count+")",thisweek_test_over_tasks_path %>
  <%=link_to "需发外网("+@tasks_deliver_count+")",thisweek_deliver_tasks_path %>
</div>
<% if @tasks.blank?%>
  <div class="no_task">没有任务</div>
<%else%>
<div class="task_list">
  <table>
    <tr class="include_link_th">
      <th>任务名</th><th>需求人员</th><th>开发人员</th><th>测试人员</th><th>需求提交</th><th>提交测试</th><th>测试完成</th><th>发外网</th><th>当前状态</th>
    </tr>
    <%= render :partial => "tasks/tasklist" %>
</table>           
</div>
<%end%>

app/views/tasks/today.html.erb
<nav>
<%= link_to "全部",tasks_path %>
<%= link_to "本周",thisweek_tasks_path %>
<%= link_to "今日",today_tasks_path,:class=>"selected" %>
<%= link_to "我的任务",me_tasks_path%>
</nav>
<div class="sub_nav">
  <%=link_to "需提测("+@tasks_test_count+")",today_submit_test_tasks_path %>
  <%=link_to "需测试完成("+@tasks_test_over_count+")",today_test_over_tasks_path %>
  <%=link_to "需发外网("+@tasks_deliver_count+")",today_deliver_tasks_path %>
</div>
<% if @tasks.blank?%>
  <div class="no_task">没有任务</div>
<%else%>
<div class="task_list">
  <table>
    <tr class="include_link_th">
      <th>任务名</th><th>需求人员</th><th>开发人员</th><th>测试人员</th><th>需求提交</th><th>提交测试</th><th>测试完成</th><th>发外网</th><th>当前状态</th>
    </tr>
<%= render :partial => "tasks/tasklist" %>
</table>           
</div>
<%end%>