config/routes.rb
TaskTracker::Application.routes.draw do

  root :to => 'tasks#index' 
  resources :tasks do
    collection do
      get  :today
      get  :today_submit_test
      get  :today_test_over
      get  :today_deliver
      get  :search
      get  :by_user
      get  :by_state
      get  :me
      get  :thisweek
      get  :thisweek_submit_test
      get  :thisweek_test_over
      get  :thisweek_deliver
    end
    resources :task_histories
  end

  resources :users
end

app/models/task_history.rb
# encoding: utf-8 
class TaskHistory < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
  belongs_to :state
  has_many :attachments,:dependent => :destroy
  accepts_nested_attributes_for :attachments 
  validates_presence_of :content,:message => "内容不能为空"
  default_scope order('created_at DESC')  
end

app/controllers/task_histories_controller.rb
# encoding: utf-8
class TaskHistoriesController < ApplicationController
  before_filter :find_task,:get_user

  def create 
    if @user.blank?
       flash[:notice] = '修改状态失败，您没有权限'
    else
      @task.state_id = params[:task_history][:state_id]
      params[:task_history][:user_id] = @user.id
      @task_history = @task.task_histories.build( params[:task_history] )
      if @task_history.save && @task.save 
         flash[:notice] = '任务状态修改成功'
      else
         flash[:notice] = '任务状态修改失败'
      end
    end 
    redirect_to task_path(@task)
  end

  def destroy
    @task_history = TaskHistory.find(params[:id])
    @task_history.destroy
    redirect_to task_path(@task)
  end

  protected

  def find_task
    @task = Task.find(params[:task_id])
  end

  def get_user
    @user = User.find_by_bind_ip(request.remote_ip)
  end
  
end

app/helpers/task_histories_helper.rb
module TaskHistoriesHelper
end

app/views/task_histories/_task_history.html.erb
<div class="task_histories_outer">
  <h1>任务历史</h1>
  <% if @task.task_histories.blank? %>
    <div class="no_task">暂无历史</div>
  <% else %>
    <div class="history_item_container">
    <% @task.task_histories.each do |history| %>
      <div class="task_history_item">
        <div class="task_history_meta">
          <%= history.state.name %><br/><%= history.user.name %><br/><%= time_ago_in_words history.created_at %><br/>
          <% for attachment in history.attachments %><%= link_to attachment.document.original_filename, attachment.document.url %><% end %><br/>
          <%=  link_to '删除', task_task_history_path(@task,history),:method=> :delete,:confirm => '确定删除？' %>
        </div>
        <div class="history_content"> <%= simple_format history.content %> </div> 
        <div class="clear"></div>
   </div>
  <% end %>
    </div>
<% end %>
</div>