config/routes.rb
TaskTracker::Application.routes.draw do

  root :to => 'tasks#index' 
  resources :tasks do
    collection do
      get  :today
      get  :today_submit_test
      get  :today_test_over
      get  :today_deliver
      get  :search
      get  :by_user
      get  :by_state
      get  :me
      get  :thisweek
      get  :thisweek_submit_test
      get  :thisweek_test_over
      get  :thisweek_deliver
    end
    resources :task_histories
  end

  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :task_user_ships,:dependent => :destroy
  has_many :tasks,:through => :task_user_ships
  belongs_to :department
  has_many :task_histories,:dependent => :destroy
  validates :name,:presence => true
  validates_uniqueness_of :bind_ip
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
   if @user.update_attributes(params[:user])
     flash[:notice] = '用户编辑成功'
     redirect_to users_url
   else
     render :action => "edit"
   end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = '成功添加用户'
      redirect_to users_url
    else
      render :action => 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = '用户已成功删除'
    redirect_to users_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def department_options
    Department.all.map{|s| [s.name,s.id]}
  end
end

app/views/users/edit.html.erb
<div class="edit_task_page_title">
编辑用户：<%= @user.name %>
</div>
 <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="edit_task_form">
  <%= form_for @user do |t|%>
    <table class="edit_task_table">
      <tr>
        <td class="task_attr_name">名字：</td><td><%= t.text_field :name,:required=>true %></td>
      </tr>
      <tr>
        <td class="task_attr_name">IP：</td><td><%= t.text_field :bind_ip,:pattern=>'\d+\.\d+\.\d+\.\d+',:title=>'例如：192.168.1.155'%></td>
      </tr>
      <tr>
        <td class="task_attr_name">部门：</td><td><%= t.select :department_id, department_options %></td>
      </tr> 
    </table>
    <div class="edit_task_submit_outer"> <%= t.submit '更新用户' %> </div>
  <%end%>
</div>
<div class="related_link_group">
  <%= link_to raw('<span class="leftarrow icon"></span>返回用户列表'), users_path,:class=>'back button'%>
  <%= link_to raw('<span class="trash icon"></span>删除此用户') , @user,:method=> :delete,:confirm => '确定删除？',:class=>'negative button'%>
</div>

app/views/users/index.html.erb
<div class="edit_task_page_title">用户列表</div>
<% if @users.blank? %>
	<div class="no_task">没人</div>
<% else%>
	<div class="task_list">
		<table>
			<tr><th>名字</th><th>绑定IP</th><th>部门</th></tr>
		<% for user in @users %>
		<tr>
			<td><%= link_to user.name,edit_user_path(user),:title=>'编辑' %></td>
			<td><%= user.bind_ip %></td>
			<td><%= user.department.name %></td>
		</tr>
		<% end %>
	</table>
	</div>
      <% end %>
      <div>
<%= link_to raw('<span class="plus icon"></span>添加新用户'),new_user_path,:class => "button " %>
        <%= link_to raw('<span class="leftarrow icon"></span>返回任务列表'), tasks_path,:class=>'back button'%>
      </div>

app/views/users/new.html.erb
<div class="edit_task_page_title">
添加用户：
</div>
 <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="edit_task_form">
  <%= form_for @user do |t|%>
    <table class="edit_task_table">
      <tr>
        <td class="task_attr_name">名字：</td><td><%= t.text_field :name,:required=>true %></td>
      </tr>
      <tr>
        <td class="task_attr_name">IP：</td><td><%= t.text_field :bind_ip,:pattern=>'\d+\.\d+\.\d+\.\d+',:title=>'例如：127.0.0.1' %></td>
      </tr>
      <tr>
        <td class="task_attr_name">部门：</td><td><%= t.select :department_id, department_options %></td>
      </tr> 
    </table>
    <div class="edit_task_submit_outer"> <%= t.submit '添加用户' %> </div>
  <%end%>
</div>
<div class="related_link_group">
  <%= link_to raw('<span class="leftarrow icon"></span>返回用户列表'), users_path,:class=>'back button'%>
</div>